export const CREATE_IMGSECTION = "CREATE_IMGSECTION";
export const RETRIEVE_IMGSECTIONS = "RETRIEVE_IMGSECTIONS";
export const RETRIEVE_IMGSECION_ID = "RETRIEVE_IMGSECION_ID"
export const UPDATE_IMGSECTION = "UPDATE_IMGSECTION";
export const DELETE_IMGSECTION = "DELETE_IMGSECTION";
export const DELETE_ALL_IMGSECTIONS = "DELETE_ALL_IMGSECTIONS";

export const CREATE_IMGCATOGERY = "CREATE_IMGCATOGERY";
export const RETRIEVE_IMGCATOGERIES = "RETRIEVE_IMGCATOGERIES";
export const RETRIEVE_IMGCATOGERY_ID = "RETRIEVE_IMGCATOGERY_ID";
export const UPDATE_IMGCATOGERY = "UPDATE_IMGCATOGERY";
export const DELETE_IMGCATOGERY = "DELETE_IMGCATOGERY";
export const DELETE_ALL_IMGCATOGERIES = "DELETE_ALL_IMGCATOGERIES";

export const CREATE_IMGCDATA = "CREATE_IMGCDATA";
export const RETRIEVE_IMGDATAS = "RETRIEVE_IMGDATAS";
export const UPDATE_IMGDATA = "UPDATE_IMGDATA";
export const DELETE_IMGDATA = "DELETE_IMGDATA";
export const DELETE_ALL_IMGDATAS = "DELETE_ALL_IMGDATAS";

export const SET_DATA_MESSAGE = "SET_DATA_MESSAGE"
export const CLEAR_DATA_MESSAGE = "CLEAR_DATA_MESSAGE"
